apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: tahk1g1d8-nodejs
  janus-idp.io/tekton: tahk1g1d8-nodejs
  backstage.io/kubernetes-id: tahk1g1d8-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: tahk1g1d8-nodejs
resources:
- deployment.yaml
- route.yaml
- service.yaml
